minTlsServeVersion: 1.3
connectIPVersion: dual

ports:
  dns: 53
  http: 4000

log:
  level: info
  format: text
  timestamp: true
  privacy: false

upstreams:
  init:
    strategy: blocking
  groups:
    default:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
      #- tcp-tls:1.1.1.1:853
      #- tcp-tls:1.0.0.1:853
  strategy: parallel_best
  timeout: 2s

bootstrapDns:
  #- tcp+udp:1.1.1.1
  #- tcp-tls:1.1.1.1:853
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  
clientLookup:
  upstream: 10.0.0.1
  singleNameOrder:
    - 2
    - 1

blocking:
  denylists:
    default:
      #- https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      - https://adaway.org/hosts.txt
      #- https://www.malwaredomainlist.com/hostslist/hosts.txt
      - https://someonewhocares.org/hosts/zero/hosts
      #- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
      #- https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
      #- https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      #- https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
      #- https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
      #- https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      #- https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
      - https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://www.github.developerdan.com/hosts/lists/facebook-extended.txt
      - https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
      - https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/alexa
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/apple
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/huawei
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/roku
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/sonos
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/windows
      - https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi
  clientGroupsBlock:
    default:
      - default
  blockType: nxDomain
  blockTTL: 1m
  loading:
    refreshPeriod: 24h
    downloads:
      timeout: 30s
      writeTimeout: 30s
      readTimeout: 30s
      readHeaderTimeout: 30s
      attempts: 3
      cooldown: 10s
    concurrency: 8
    strategy: blocking
    maxErrorsPerSource: 5

prometheus:
  enable: true
  path: /metrics