---

services:
  #adguard:
  #  container_name: adguard
  #  hostname: adguard
  #  image: adguard/adguardhome:v0.107.62
  #  restart: always
  #  ports:
  #    - 53:53/tcp
  #    - 53:53/udp
  #    - 80:80/tcp
  #    - 3000:3000/tcp
  #  volumes:
  #    - adguard:/opt/adguardhome/work
  #    - adguard:/opt/adguardhome/conf
  #  labels:
  #    tsdproxy.enable: "true"
  #    tsdproxy.ephemeral: "false"
  #    tsdproxy.authkey: ${tailscale_auth_key}
  #   tsdproxy.container_port: 80

  #adguard-exporter:
  #  container_name: adguard-exporter
  #  hostname: adguard-exporter
  #  image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.0
  #  restart: always
  #  ports:
  #    - 9618:9618
  #  environment:
  #    - ADGUARD_SERVERS=http://adguard
  #    - ADGUARD_USERNAMES=${adguard_username}
  #    - ADGUARD_PASSWORDS=${adguard_password}
  #    - INTERVAL=30s
  #    - DEBUG=false

  alloy:
    image: grafana/alloy:v1.9.2
    container_name: alloy
    hostname: alloy
    volumes:
      - ./docker-configs/alloy/config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy

  blocky:
    image: ghcr.io/0xerr0r/blocky:v0.26.2
    container_name: blocky
    hostname: blocky
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 4000:4000/tcp
    environment:
      - TZ=${timezone}
    volumes:
      - /etc/localtime:/etc/localtime:ro # synchronize log timestamp with host
      - ./docker-configs/blocky/config.yaml:/app/config.yml:ro

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    command:
      - '-port=8098'
    ports:
      - 8098:8098
    environment:
      - CADVISOR_HEALTHCHECK_URL=http://localhost:8098/healthz
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:v1.9.1
    ports:
      - 9100:9100
    restart: unless-stopped

  tsdproxy:
    image: ghcr.io/almeidapaulopt/tsdproxy:1.4.7
    hostname: tsdproxy
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - tsdproxy_config:/config
      - tsdproxy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  adguard:
    name: adguard

  tsdproxy_config:
    name: tsdproxy_config

  tsdproxy_data:
    name: tsdproxy_data
