---

services:
  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:v0.107.54
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - adguard:/opt/adguardhome/work
      - adguard:/opt/adguardhome/conf

  adguard-exporter:
    container_name: adguard-exporter
    hostname: adguard-exporter
    image: ebrianne/adguard-exporter:v1.14
    restart: always
    ports:
      - 9617:9617
    environment:
      - adguard_protocol=http
      - adguard_hostname=adguard
      - adguard_username=${adguard_username}
      - adguard_password=${adguard_password}
      - interval=10s
      - log_limit=10000

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:v1.8.2
    ports:
      - 9100:9100
    restart: unless-stopped

volumes:
  adguard:
    name: adguard
