---

services:
  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:v0.107.68
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - adguard:/opt/adguardhome/work
      - adguard:/opt/adguardhome/conf
    labels:
      tsdproxy.enable: "true"
      tsdproxy.ephemeral: "false"
      tsdproxy.authkey: ${tailscale_auth_key}
      tsdproxy.container_port: 80

  adguard-exporter:
    container_name: adguard-exporter
    hostname: adguard-exporter
    image: ghcr.io/henrywhitaker3/adguard-exporter:v1.2.1
    restart: always
    ports:
      - 9618:9618
    environment:
      - ADGUARD_SERVERS=http://adguard
      - ADGUARD_USERNAMES=${adguard_username}
      - ADGUARD_PASSWORDS=${adguard_password}
      - INTERVAL=30s
      - DEBUG=false

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    command:
      - '-port=8098'
    ports:
      - 8098:8098
    environment:
      - CADVISOR_HEALTHCHECK_URL=http://localhost:8098/healthz
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:v1.10.2
    ports:
      - 9100:9100
    restart: unless-stopped

  tsdproxy:
    image: ghcr.io/almeidapaulopt/tsdproxy:1.4.7
    hostname: tsdproxy
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - tsdproxy_config:/config
      - tsdproxy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  adguard:
    name: adguard

  tsdproxy_config:
    name: tsdproxy_config

  tsdproxy_data:
    name: tsdproxy_data
